TARGETS=*.c
CC=gcc

first: cezar.c
	$(CC) cezar.c -o crypt
	./crypt
	cat output.txt
	
second: decript.c
	$(CC) decript.c -o decript
	./decript
	cat input_reload.txt
	
third: variant.c
	$(CC) variant.c -o variant
	./variant
	cat all.txt
	
fourth: glossary.c
	$(CC) glossary.c -o glossary
	./glossary
